name: "Setup EcoScalpel CLI"
description: Install the EcoScalpel CLI for cost and sustainability analysis of Scaleway Terraform projects.
branding:
  icon: activity
  color: purple
inputs:
  install-dir:
    description: Directory where the EcoScalpel binary will be stored.
    default: ${{ runner.temp }}/ecoscalpel/bin
  api-key:
    description: EcoScalpel API key stored in the CLI config (masked).
    default: ""
  version:
    description: >
      EcoScalpel release version to install (e.g. v0.8.1). Use "latest" to pull
      the most recent GitHub release automatically.
    default: latest
outputs:
  ecoscalpel-path:
    description: Absolute path to the EcoScalpel binary.
    value: ${{ steps.build.outputs.cli_path }}
runs:
  using: composite
  steps:
    - name: Install EcoScalpel binary
      id: build
      shell: bash
      env:
        INSTALL_DIR: ${{ inputs['install-dir'] }}
        VERSION: ${{ inputs.version }}
      run: |
        set -euo pipefail

        install_dir="${INSTALL_DIR}"
        mkdir -p "$install_dir"

        owner="didier-segura"
        repo="ecoscalpel"
        version="${VERSION}"
        if [ "$version" = "latest" ]; then
          version="$(curl -fsSL "https://api.github.com/repos/$owner/$repo/releases/latest" | jq -r '.tag_name')"
        fi
        if [ -z "$version" ] || [ "$version" = "null" ]; then
          echo "::error::Failed to determine EcoScalpel release version"
          exit 1
        fi

        os="$(uname -s | tr '[:upper:]' '[:lower:]')"
        arch="$(uname -m)"
        case "$arch" in
          x86_64) arch="amd64" ;;
          aarch64|arm64) arch="arm64" ;;
          *) echo "::error::Unsupported architecture: $arch"; exit 1 ;;
        esac

        asset="ecoscalpel_${os}_${arch}.tar.gz"
        url="https://github.com/$owner/$repo/releases/download/${version}/${asset}"

        tmp_dir="$(mktemp -d)"
        archive="$tmp_dir/$asset"
        echo "Downloading $url"
        curl -fsSL "$url" -o "$archive"
        tar -xzf "$archive" -C "$tmp_dir"

        if [ ! -f "$tmp_dir/ecoscalpel" ]; then
          echo "::error::Downloaded archive did not contain ecoscalpel binary"
          exit 1
        fi
        mv "$tmp_dir/ecoscalpel" "$install_dir/ecoscalpel"

        chmod +x "$install_dir/ecoscalpel"
        echo "$install_dir" >> "$GITHUB_PATH"
        echo "cli_path=$(cd "$install_dir" && pwd)/ecoscalpel" >> "$GITHUB_OUTPUT"

    - name: Configure EcoScalpel credentials
      if: ${{ inputs.api-key != '' }}
      shell: bash
      env:
        API_KEY: ${{ inputs.api-key }}
      run: |
        set -euo pipefail

        echo "::add-mask::$API_KEY"
        config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/ecoscalpel"
        config_file="$config_dir/config.json"
        mkdir -p "$config_dir"

        python3 - "$config_file" <<'PY'
import json, os, sys, datetime

cfg_path = sys.argv[1]
api_key = os.environ["API_KEY"]
now = datetime.datetime.utcnow().replace(microsecond=0).isoformat() + "Z"

cfg = {}
try:
    with open(cfg_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
except FileNotFoundError:
    pass
except Exception as exc:
    print(f"::warning::Could not parse existing config {cfg_path}: {exc}")

cfg["api_key"] = api_key
cfg["updated_at"] = now

with open(cfg_path, "w", encoding="utf-8") as f:
    json.dump(cfg, f, indent=2)
PY
