name: "Setup EcoScalpel CLI"
description: Install the EcoScalpel CLI for cost and sustainability analysis of Scaleway Terraform projects.
branding:
  icon: activity
  color: purple
inputs:
  install_dir:
    description: Directory where the EcoScalpel binary will be stored.
    default: ${{ runner.temp }}/ecoscalpel/bin
  api-key:
    description: EcoScalpel API key stored in the CLI config (masked).
    default: ""
  download_url:
    description: Direct download URL for the EcoScalpel binary. Overrides the version-based download.
    default: ""
  version:
    description: >
      EcoScalpel release tag to install (e.g. prod-0.0.7). Required when download_url is not provided.
    default: ""
  token:
    description: Optional GitHub token used to authenticate download requests for private repositories.
    default: ""
outputs:
  ecoscalpel-path:
    description: Absolute path to the EcoScalpel binary.
    value: ${{ steps.build.outputs.cli_path }}
runs:
  using: composite
  steps:
    - name: Install EcoScalpel binary
      id: build
      shell: bash
      env:
        INSTALL_DIR: ${{ inputs.install_dir }}
        VERSION: ${{ inputs.version }}
      run: |
        set -euo pipefail

        install_dir="${INSTALL_DIR}"
        mkdir -p "$install_dir"

        TOKEN="${{ inputs.token }}"

        if [ -n "${{ inputs.download_url }}" ]; then
          asset_url="${{ inputs.download_url }}"
        else
          if [ -z "$VERSION" ]; then
            echo "::error::Either download_url must be provided or version must be set."
            exit 1
          fi

          os="$(uname -s | tr '[:upper:]' '[:lower:]')"
          arch="$(uname -m)"
          case "$arch" in
            x86_64) arch="amd64" ;;
            aarch64|arm64) arch="arm64" ;;
            *) echo "::error::Unsupported architecture: $arch"; exit 1 ;;
          esac

          asset_url="https://github.com/didier-segura/ecoscalpel/releases/download/${VERSION}/ecoscalpel-${os}-${arch}"
        fi

        asset_name="$(basename "$asset_url")"

        tmp_dir="$(mktemp -d)"
        archive="$tmp_dir/$asset_name"
        echo "Downloading $asset_url"
        curl_cmd=(curl -fsSL)
        if [ -n "$TOKEN" ]; then
          curl_cmd+=(-H "Authorization: Bearer $TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" -H "Accept: application/octet-stream")
        fi
        curl_cmd+=("$asset_url" -o "$archive")
        "${curl_cmd[@]}"

        case "$archive" in
          *.tar.gz|*.tgz) tar -xzf "$archive" -C "$tmp_dir" ;;
          *.zip) unzip -q "$archive" -d "$tmp_dir" ;;
          *)
            chmod +x "$archive"
            extracted_binary="$archive"
            ;;
        esac

        if [ -z "${extracted_binary:-}" ]; then
          extracted_binary="$(find "$tmp_dir" -maxdepth 2 -type f -name 'ecoscalpel' | head -n1)"
        fi
        if [ -z "$extracted_binary" ]; then
          echo "::error::Downloaded archive did not contain ecoscalpel binary"
          exit 1
        fi
        mv "$extracted_binary" "$install_dir/ecoscalpel"

        chmod +x "$install_dir/ecoscalpel"
        echo "$install_dir" >> "$GITHUB_PATH"
        echo "cli_path=$(cd "$install_dir" && pwd)/ecoscalpel" >> "$GITHUB_OUTPUT"
